# Generated by Django 3.1.7 on 2021-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20210326_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='payments',
            name='voucher_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
