# Generated by Django 3.1.7 on 2021-03-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20210326_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='per_person_amt',
            field=models.IntegerField(default=None),
        ),
    ]
