# Generated by Django 3.1.7 on 2021-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_package_per_person_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='per_person_amt',
            field=models.IntegerField(),
        ),
    ]
