# Generated by Django 3.1.7 on 2021-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_auto_20210327_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='advance_amt',
            field=models.IntegerField(default=0),
        ),
    ]
