# Generated by Django 3.1.7 on 2021-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_payments_advance_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='advance_amt',
        ),
    ]
