# Generated by Django 3.1.7 on 2021-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_auto_20210408_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_destination',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
