# Generated by Django 3.1.7 on 2021-04-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_auto_20210409_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_hotel',
            field=models.CharField(choices=[('Annapurna', 'Hotel Del Annapurna'), ('Hyatt', 'Hyatt regency'), ('Malla ', 'Hotel malla'), ('Everest', 'Hotel Everest'), ('Mahakali', 'Hotel Mahakali')], max_length=200),
        ),
    ]
