# Generated by Django 3.1.7 on 2021-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_auto_20210409_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number_of_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='per_person_amt',
            field=models.PositiveIntegerField(),
        ),
    ]
