# Generated by Django 3.1.7 on 2021-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0015_auto_20210409_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_people',
            field=models.IntegerField(),
        ),
    ]
