# Generated by Django 3.1.7 on 2021-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_auto_20210409_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_number_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='per_person_amt',
            field=models.IntegerField(),
        ),
    ]
